name: manual execute github secret workflow

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Select the browser to run the tests on
        default: chrome
        options:
          - chrome
          - firefox
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      
      - name: Verify Chrome
        run: google-chrome --version
        
      - name: Build and Test with Maven
        working-directory: SeleniumDemo
        env:
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: mvn clean test -Dbrowser=${{ github.event.inputs.browser}}
          
